# This is a basic workflow to help you get started with Actions

name: PvP Talent Swapper

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: xpol/setup-lua@v0.2
        with:
          lua-version: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v2

      # installs luarocks package manager and busted unit test
      - name: Install busted and compile
        run: |
          luarocks make
          luarocks install busted
          luarocks install luacov
        
      - name: Run Tests
        run: |
          busted -o -c -v utfTerminal
          
